Update azure-pipelines-old.yml for Azure Pipelines

diff --git a/azure-pipelines-old.yml b/azure-pipelines-old.yml
--- a/azure-pipelines-old.yml
+++ b/azure-pipelines-old.yml
@@ -43,5 +43,72 @@ steps:
       runOptions: inline
 
       inline: |
-        # update deployment image
-        kubectl set image deployment/azureplpelineweb azureplpelineweb=$(imageName) --record=true
+        # stop container
+        containers=$(docker ps -q --filter name=azureplpelineweb)
+        if test -n "$containers"; 
+        then
+        docker stop $(docker ps -q --filter name=azureplpelineweb) >> /dev/null 2>&1
+        rc=$?
+        if [[ $rc != 0 ]];
+        then
+        echo 'failed to stop container...'
+        exit $rc;
+        fi
+        fi
+    
+        # remove container
+        containers1=$(docker ps -q -a --filter name=azureplpelineweb)
+        if test -n "$containers1"; 
+        then
+        docker rm $(docker ps -q -a --filter name=azureplpelineweb) >> /dev/null 2>&1
+        rc=$?
+        if [[ $rc != 0 ]];
+        then
+        echo 'failed to remove container...'
+        exit $rc;
+        fi
+        fi
+
+        # remove image
+        containers2=$(docker images | grep azureplpelineweb | awk '{print $3}')
+        if test -n "$containers2"; 
+        then
+        docker rmi $(docker images | grep azureplpelineweb | awk '{print $3}') >> /dev/null 2>&1
+        rc=$?
+        if [[ $rc != 0 ]];
+        then
+        echo 'failed to remove image...'
+        exit $rc;
+        fi
+        fi
+      
+        # pull newest image
+        docker pull $(imageName) >> /dev/null 2>&1
+        rc=$?
+        if [[ $rc != 0 ]];
+        then
+        echo 'failed to pull container...'
+        exit $rc;
+        fi
+      
+        # run image
+        docker run -d -p 8083:80 --name azureplpelineweb $(imageName) >> /dev/null 2>&1
+        rc=$?
+        if [[ $rc != 0 ]];
+        then
+        echo 'failed to run container...'
+        exit $rc;
+        fi
+      
+        # remove useless images
+        danglings=$(docker images -f "dangling=true" -q)
+        if test -n "$danglings";
+        then
+        docker rmi $(docker images -f "dangling=true" -q) >> /dev/null 2>&1
+        rc=$?
+        if [[ $rc != 0 ]];
+        then
+        echo 'failed to remove danglings container...'
+        exit $rc;
+        fi
+        fi
