Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -8,7 +8,7 @@ pool:
 
 variables:
   tagName: '$(Build.BuildNumber)'
-  imageName: '$(dockerId)/azurePlpelineWeb:$(tagName)'
+  imageName: 'azurePlpelineWeb'
 
 steps:
 
@@ -26,8 +26,59 @@ steps:
 - task: SSH@0
   displayName: 'Run shell inline on remote machine'
   inputs:
-    sshEndpoint: 'weihanli-vm'
+    sshEndpoint: 'aliyun_centos'
     runOptions: inline
 
     inline: |
-      docker set image deployment/azurePlpelineWeb azurePlpelineWeb=$(imageName) --record=true
+      containers=$(docker ps -q --filter name=$(imageName))
+      if test -n "$containers"; 
+      then
+      docker stop $(docker ps -q --filter name=$(imageName)) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to stop container...'
+       exit $rc;
+      fi
+      fi
+     
+      containers1=$(docker ps -q -a --filter name=$(imageName))
+      if test -n "$containers1"; 
+      then
+      docker rm $(docker ps -q -a --filter name=$(imageName)) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to remove container...'
+       exit $rc;
+      fi
+      fi
+     
+     
+      docker pull $(imageName):latest >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to pull container...'
+       exit $rc;
+      fi
+     
+      docker run -d -p 80:80 --name $(imageName)  >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to run container...'
+       exit $rc;
+      fi
+     
+      danglings=$(docker images -f "dangling=true" -q)
+      if test -n "$danglings";
+      then
+      docker rmi $(docker images -f "dangling=true" -q) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to remove danglings container...'
+       exit $rc;
+      fi
+      fi
